name: niunamuertevial
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha55989b_3
  - asttokens=2.1.0=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - autopep8=2.0.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - black=22.10.0=py39hcbf5309_2
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py39ha55989b_1005
  - bs4=4.11.1=hd8ed1ab_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.9.24=h5b45459_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py39h68f70e3_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.6=py39h1f6ef14_0
  - cryptography=38.0.3=py39h58e9bdb_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py39h99910a6_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py39ha55989b_1
  - freetype=2.12.1=h546665d_0
  - gettext=0.21.1=h5728263_0
  - glib=2.74.1=h12be248_1
  - glib-tools=2.74.1=h12be248_1
  - gst-plugins-base=1.20.3=h001b923_2
  - gstreamer=1.20.3=h6b5321d_2
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.0.0=pyha770c72_1
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h57928b3_3787
  - ipykernel=6.17.1=pyh025b116_0
  - ipython=8.6.0=pyh08f2357_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h8ffe710_2
  - jsonschema=4.17.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hcbf5309_7
  - jupyter_client=7.4.7=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=5.0.0=py39hcbf5309_0
  - jupyter_server=1.23.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39h1f6ef14_1
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang=14.0.6=default_h77d9078_0
  - libclang13=14.0.6=default_h77d9078_0
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.74.1=he8f3873_1
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=16_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.38=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.40.0=hcfcfb64_0
  - libtiff=4.4.0=h8e97e67_4
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.4=h8ffe710_0
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.3=hc3477c8_0
  - libxslt=1.1.37=h0192164_0
  - libzlib=1.2.13=hcfcfb64_4
  - lxml=4.9.1=py39h0942119_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py39ha55989b_2
  - matplotlib=3.6.2=py39hcbf5309_0
  - matplotlib-base=3.6.2=py39haf65ace_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py39hcbf5309_6
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.5=pyhd8ed1ab_0
  - nbconvert-core=7.2.5=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.5=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=hc9384bd_1
  - openpyxl=3.0.10=py39ha55989b_2
  - openssl=1.1.1s=hcfcfb64_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.19.2=h57928b3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.10.2=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39h595c93f_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - ply=3.11=py_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.32=pyha770c72_0
  - prompt_toolkit=3.0.32=hd8ed1ab_0
  - psutil=5.9.4=py39ha55989b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.9.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39hb08f45d_0
  - pyqt5-sip=12.11.0=py39h415ef7b_0
  - pyrsistent=0.19.2=py39ha55989b_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.13=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=0.21.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pywin32=304=py39h99910a6_2
  - pywinpty=2.0.9=py39h99910a6_0
  - pyzmq=24.0.1=py39hea35a22_1
  - qt=5.15.4=h2d74725_0
  - qt-main=5.15.4=h467ea89_2
  - qt-webengine=5.15.4=h7325c83_3
  - qtconsole=5.4.0=pyhd8ed1ab_0
  - qtconsole-base=5.4.0=pyha770c72_0
  - qtpy=2.3.0=pyhd8ed1ab_0
  - requests=2.28.1=pyhd8ed1ab_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sip=6.6.2=py39h415ef7b_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=hcfcfb64_0
  - stack_data=0.6.1=pyhd8ed1ab_0
  - tbb=2021.7.0=h91493d7_0
  - terminado=0.17.0=pyh08f2357_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py39ha55989b_1
  - traitlets=5.5.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022f=h191b570_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py39ha55989b_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - vc=14.3=h3d8a991_9
  - vs2015_runtime=14.32.31332=h1d6e394_9
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wincertstore=0.2=pyhd8ed1ab_1009
  - winpty=0.4.3=4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h7755175_4
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - datasets==1.18.4
    - dill==0.3.5.1
    - emoji==1.7.0
    - filelock==3.8.0
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - huggingface-hub==0.8.1
    - joblib==1.1.0
    - multidict==6.0.2
    - multiprocess==0.70.13
    - numpy==1.23.2
    - pandas==1.4.3
    - pyarrow==9.0.0
    - pysentimiento==0.4.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - regex==2022.7.25
    - responses==0.18.0
    - sacremoses==0.0.53
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - sklearn==0.0
    - threadpoolctl==3.1.0
    - tokenizers==0.10.3
    - torch==1.12.1
    - tqdm==4.64.0
    - transformers==4.13.0
    - xxhash==3.0.0
    - yarl==1.8.1